export const mockBreeds = [
 {
  weight: {
   imperial: '7  -  10',
   metric: '3 - 5',
  },
  id: 'abys',
  name: 'Abyssinian',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/abyssinian',
  vcahospitals_url:
   'https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian',
  temperament: 'Active, Energetic, Independent, Intelligent, Gentle',
  origin: 'Egypt',
  country_codes: 'EG',
  country_code: 'EG',
  description:
   'The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.',
  life_span: '14 - 15',
  indoor: 0,
  lap: 1,
  alt_names: '',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 3,
  dog_friendly: 4,
  energy_level: 5,
  grooming: 1,
  health_issues: 2,
  intelligence: 5,
  shedding_level: 2,
  social_needs: 5,
  stranger_friendly: 5,
  vocalisation: 1,
  experimental: 0,
  hairless: 0,
  natural: 1,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Abyssinian_(cat)',
  hypoallergenic: 0,
  reference_image_id: '0XYvRd7oD',
  image: {
   id: '0XYvRd7oD',
   width: 1204,
   height: 1445,
   url: 'https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg',
  },
 },
 {
  weight: {
   imperial: '7 - 10',
   metric: '3 - 5',
  },
  id: 'aege',
  name: 'Aegean',
  vetstreet_url: 'http://www.vetstreet.com/cats/aegean-cat',
  temperament: 'Affectionate, Social, Intelligent, Playful, Active',
  origin: 'Greece',
  country_codes: 'GR',
  country_code: 'GR',
  description:
   'Native to the Greek islands known as the Cyclades in the Aegean Sea, these are natural cats, meaning they developed without humans getting involved in their breeding. As a breed, Aegean Cats are rare, although they are numerous on their home islands. They are generally friendly toward people and can be excellent cats for families with children.',
  life_span: '9 - 12',
  indoor: 0,
  alt_names: '',
  adaptability: 5,
  affection_level: 4,
  child_friendly: 4,
  dog_friendly: 4,
  energy_level: 3,
  grooming: 3,
  health_issues: 1,
  intelligence: 3,
  shedding_level: 3,
  social_needs: 4,
  stranger_friendly: 4,
  vocalisation: 3,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Aegean_cat',
  hypoallergenic: 0,
  reference_image_id: 'ozEvzdVM-',
  image: {
   id: 'ozEvzdVM-',
   width: 1200,
   height: 800,
   url: 'https://cdn2.thecatapi.com/images/ozEvzdVM-.jpg',
  },
 },
 {
  weight: {
   imperial: '7 - 16',
   metric: '3 - 7',
  },
  id: 'abob',
  name: 'American Bobtail',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanBobtail.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/american-bobtail',
  vcahospitals_url:
   'https://vcahospitals.com/know-your-pet/cat-breeds/american-bobtail',
  temperament: 'Intelligent, Interactive, Lively, Playful, Sensitive',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   'American Bobtails are loving and incredibly intelligent cats possessing a distinctive wild appearance. They are extremely interactive cats that bond with their human family with great devotion.',
  life_span: '11 - 15',
  indoor: 0,
  lap: 1,
  alt_names: '',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 3,
  grooming: 1,
  health_issues: 1,
  intelligence: 5,
  shedding_level: 3,
  social_needs: 3,
  stranger_friendly: 3,
  vocalisation: 3,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 1,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/American_Bobtail',
  hypoallergenic: 0,
  reference_image_id: 'hBXicehMA',
  image: {
   id: 'hBXicehMA',
   width: 1600,
   height: 951,
   url: 'https://cdn2.thecatapi.com/images/hBXicehMA.jpg',
  },
 },
 {
  weight: {
   imperial: '5 - 10',
   metric: '2 - 5',
  },
  id: 'acur',
  name: 'American Curl',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanCurl.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/american-curl',
  vcahospitals_url:
   'https://vcahospitals.com/know-your-pet/cat-breeds/american-curl',
  temperament:
   'Affectionate, Curious, Intelligent, Interactive, Lively, Playful, Social',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   'Distinguished by truly unique ears that curl back in a graceful arc, offering an alert, perky, happily surprised expression, they cause people to break out into a big smile when viewing their first Curl. Curls are very people-oriented, faithful, affectionate soulmates, adjusting remarkably fast to other pets, children, and new situations.',
  life_span: '12 - 16',
  indoor: 0,
  lap: 1,
  alt_names: '',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 3,
  grooming: 2,
  health_issues: 1,
  intelligence: 3,
  shedding_level: 3,
  social_needs: 3,
  stranger_friendly: 3,
  vocalisation: 3,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/American_Curl',
  hypoallergenic: 0,
  reference_image_id: 'xnsqonbjW',
  image: {
   id: 'xnsqonbjW',
   width: 1000,
   height: 964,
   url: 'https://cdn2.thecatapi.com/images/xnsqonbjW.jpg',
  },
 },
 {
  weight: {
   imperial: '8 - 15',
   metric: '4 - 7',
  },
  id: 'asho',
  name: 'American Shorthair',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanShorthair.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/american-shorthair',
  vcahospitals_url:
   'https://vcahospitals.com/know-your-pet/cat-breeds/american-shorthair',
  temperament: 'Active, Curious, Easy Going, Playful, Calm',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   'The American Shorthair is known for its longevity, robust health, good looks, sweet personality, and amiability with children, dogs, and other pets.',
  life_span: '15 - 17',
  indoor: 0,
  lap: 1,
  alt_names: 'Domestic Shorthair',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 3,
  grooming: 1,
  health_issues: 3,
  intelligence: 3,
  shedding_level: 3,
  social_needs: 4,
  stranger_friendly: 3,
  vocalisation: 3,
  experimental: 0,
  hairless: 0,
  natural: 1,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/American_Shorthair',
  hypoallergenic: 0,
  reference_image_id: 'JFPROfGtQ',
  image: {
   id: 'JFPROfGtQ',
   width: 1600,
   height: 1200,
   url: 'https://cdn2.thecatapi.com/images/JFPROfGtQ.jpg',
  },
 },
 {
  weight: {
   imperial: '8 - 15',
   metric: '4 - 7',
  },
  id: 'awir',
  name: 'American Wirehair',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanWirehair.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/american-wirehair',
  temperament:
   'Affectionate, Curious, Gentle, Intelligent, Interactive, Lively, Loyal, Playful, Sensible, Social',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   'The American Wirehair tends to be a calm and tolerant cat who takes life as it comes. His favorite hobby is bird-watching from a sunny windowsill, and his hunting ability will stand you in good stead if insects enter the house.',
  life_span: '14 - 18',
  indoor: 0,
  lap: 1,
  alt_names: '',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 3,
  grooming: 1,
  health_issues: 3,
  intelligence: 3,
  shedding_level: 1,
  social_needs: 3,
  stranger_friendly: 3,
  vocalisation: 3,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/American_Wirehair',
  hypoallergenic: 0,
  reference_image_id: '8D--jCd21',
  image: {
   id: '8D--jCd21',
   width: 1280,
   height: 936,
   url: 'https://cdn2.thecatapi.com/images/8D--jCd21.jpg',
  },
 },
 {
  weight: {
   imperial: '8 - 16',
   metric: '4 - 7',
  },
  id: 'amau',
  name: 'Arabian Mau',
  vcahospitals_url: '',
  temperament: 'Affectionate, Agile, Curious, Independent, Playful, Loyal',
  origin: 'United Arab Emirates',
  country_codes: 'AE',
  country_code: 'AE',
  description:
   'Arabian Mau cats are social and energetic. Due to their energy levels, these cats do best in homes where their owners will be able to provide them with plenty of playtime, attention and interaction from their owners. These kitties are friendly, intelligent, and adaptable, and will even get along well with other pets and children.',
  life_span: '12 - 14',
  indoor: 0,
  alt_names: 'Alley cat',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 4,
  grooming: 1,
  health_issues: 1,
  intelligence: 3,
  shedding_level: 1,
  social_needs: 3,
  stranger_friendly: 3,
  vocalisation: 1,
  experimental: 0,
  hairless: 0,
  natural: 1,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Arabian_Mau',
  hypoallergenic: 0,
  reference_image_id: 'k71ULYfRr',
  image: {
   id: 'k71ULYfRr',
   width: 2048,
   height: 1554,
   url: 'https://cdn2.thecatapi.com/images/k71ULYfRr.jpg',
  },
 },
 {
  weight: {
   imperial: '7 - 15',
   metric: '3 - 7',
  },
  id: 'amis',
  name: 'Australian Mist',
  temperament: 'Lively, Social, Fun-loving, Relaxed, Affectionate',
  origin: 'Australia',
  country_codes: 'AU',
  country_code: 'AU',
  description:
   'The Australian Mist thrives on human companionship. Tolerant of even the youngest of children, these friendly felines enjoy playing games and being part of the hustle and bustle of a busy household. They make entertaining companions for people of all ages, and are happy to remain indoors between dusk and dawn or to be wholly indoor pets.',
  life_span: '12 - 16',
  indoor: 0,
  lap: 1,
  alt_names: 'Spotted Mist',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 4,
  grooming: 3,
  health_issues: 1,
  intelligence: 4,
  shedding_level: 3,
  social_needs: 4,
  stranger_friendly: 4,
  vocalisation: 3,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Australian_Mist',
  hypoallergenic: 0,
  reference_image_id: '_6x-3TiCA',
  image: {
   id: '_6x-3TiCA',
   width: 1231,
   height: 1165,
   url: 'https://cdn2.thecatapi.com/images/_6x-3TiCA.jpg',
  },
 },
 {
  weight: {
   imperial: '4 - 10',
   metric: '2 - 5',
  },
  id: 'bali',
  name: 'Balinese',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/Balinese.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/balinese',
  vcahospitals_url:
   'https://vcahospitals.com/know-your-pet/cat-breeds/balinese',
  temperament: 'Affectionate, Intelligent, Playful',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   'Balinese are curious, outgoing, intelligent cats with excellent communication skills. They are known for their chatty personalities and are always eager to tell you their views on life, love, and what you’ve served them for dinner. ',
  life_span: '10 - 15',
  indoor: 0,
  alt_names: 'Long-haired Siamese',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 5,
  grooming: 3,
  health_issues: 3,
  intelligence: 5,
  shedding_level: 3,
  social_needs: 5,
  stranger_friendly: 5,
  vocalisation: 5,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Balinese_(cat)',
  hypoallergenic: 1,
  reference_image_id: '13MkvUreZ',
  image: {
   id: '13MkvUreZ',
   width: 1600,
   height: 1000,
   url: 'https://cdn2.thecatapi.com/images/13MkvUreZ.jpg',
  },
 },
 {
  weight: {
   imperial: '4 - 9',
   metric: '2 - 4',
  },
  id: 'bamb',
  name: 'Bambino',
  temperament: 'Affectionate, Lively, Friendly, Intelligent',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   'The Bambino is a breed of cat that was created as a cross between the Sphynx and the Munchkin breeds. The Bambino cat has short legs, large upright ears, and is usually hairless. They love to be handled and cuddled up on the laps of their family members.',
  life_span: '12 - 14',
  indoor: 0,
  lap: 1,
  alt_names: '',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 5,
  grooming: 1,
  health_issues: 1,
  intelligence: 5,
  shedding_level: 1,
  social_needs: 3,
  stranger_friendly: 3,
  vocalisation: 3,
  experimental: 1,
  hairless: 1,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 1,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Bambino_cat',
  hypoallergenic: 0,
  reference_image_id: '5AdhMjeEu',
  image: {
   id: '5AdhMjeEu',
   width: 1296,
   height: 1030,
   url: 'https://cdn2.thecatapi.com/images/5AdhMjeEu.jpg',
  },
 },
 {
  weight: {
   imperial: '6 - 12',
   metric: '3 - 7',
  },
  id: 'beng',
  name: 'Bengal',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/Bengal.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/bengal',
  vcahospitals_url: 'https://vcahospitals.com/know-your-pet/cat-breeds/bengal',
  temperament: 'Alert, Agile, Energetic, Demanding, Intelligent',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   "Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
  life_span: '12 - 15',
  indoor: 0,
  lap: 0,
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  cat_friendly: 4,
  dog_friendly: 5,
  energy_level: 5,
  grooming: 1,
  health_issues: 3,
  intelligence: 5,
  shedding_level: 3,
  social_needs: 5,
  stranger_friendly: 3,
  vocalisation: 5,
  bidability: 3,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Bengal_(cat)',
  hypoallergenic: 1,
  reference_image_id: 'O3btzLlsO',
  image: {
   id: 'O3btzLlsO',
   width: 1100,
   height: 739,
   url: 'https://cdn2.thecatapi.com/images/O3btzLlsO.png',
  },
 },
 {
  weight: {
   imperial: '6 - 15',
   metric: '3 - 7',
  },
  id: 'birm',
  name: 'Birman',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/Birman.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/birman',
  vcahospitals_url: 'https://vcahospitals.com/know-your-pet/cat-breeds/birman',
  temperament: 'Affectionate, Active, Gentle, Social',
  origin: 'France',
  country_codes: 'FR',
  country_code: 'FR',
  description:
   'The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.',
  life_span: '14 - 15',
  indoor: 0,
  lap: 1,
  alt_names: 'Sacred Birman, Sacred Cat Of Burma',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 3,
  grooming: 2,
  health_issues: 1,
  intelligence: 3,
  shedding_level: 3,
  social_needs: 4,
  stranger_friendly: 3,
  vocalisation: 1,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Birman',
  hypoallergenic: 0,
  reference_image_id: 'HOrX5gwLS',
  image: {
   id: 'HOrX5gwLS',
   width: 1376,
   height: 814,
   url: 'https://cdn2.thecatapi.com/images/HOrX5gwLS.jpg',
  },
 },
 {
  weight: {
   imperial: '6 - 11',
   metric: '3 - 5',
  },
  id: 'bomb',
  name: 'Bombay',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/Bombay.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/bombay',
  vcahospitals_url: 'https://vcahospitals.com/know-your-pet/cat-breeds/bombay',
  temperament: 'Affectionate, Dependent, Gentle, Intelligent, Playful',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   "The the golden eyes and the shiny black coa of the Bopmbay is absolutely striking. Likely to bond most with one family member, the Bombay will follow you from room to room and will almost always have something to say about what you are doing, loving attention and to be carried around, often on his caregiver's shoulder.",
  life_span: '12 - 16',
  indoor: 0,
  lap: 1,
  alt_names: 'Small black Panther',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 3,
  grooming: 1,
  health_issues: 3,
  intelligence: 5,
  shedding_level: 3,
  social_needs: 4,
  stranger_friendly: 4,
  vocalisation: 5,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Bombay_(cat)',
  hypoallergenic: 0,
  reference_image_id: '5iYq9NmT1',
  image: {
   id: '5iYq9NmT1',
   width: 1250,
   height: 650,
   url: 'https://cdn2.thecatapi.com/images/5iYq9NmT1.jpg',
  },
 },
 {
  weight: {
   imperial: '8 - 18',
   metric: '4 - 8',
  },
  id: 'bslo',
  name: 'British Longhair',
  temperament:
   'Affectionate, Easy Going, Independent, Intelligent, Loyal, Social',
  origin: 'United Kingdom',
  country_codes: 'GB',
  country_code: 'GB',
  description:
   'The British Longhair is a very laid-back relaxed cat, often perceived to be very independent although they will enjoy the company of an equally relaxed and likeminded cat. They are an affectionate breed, but very much on their own terms and tend to prefer to choose to come and sit with their owners rather than being picked up.',
  life_span: '12 - 14',
  indoor: 0,
  alt_names: '',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 4,
  grooming: 5,
  health_issues: 1,
  intelligence: 5,
  shedding_level: 1,
  social_needs: 3,
  stranger_friendly: 4,
  vocalisation: 1,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/British_Longhair',
  hypoallergenic: 0,
  reference_image_id: '7isAO4Cav',
  image: {
   id: '7isAO4Cav',
   width: 960,
   height: 960,
   url: 'https://cdn2.thecatapi.com/images/7isAO4Cav.jpg',
  },
 },
 {
  weight: {
   imperial: '12 - 20',
   metric: '5 - 9',
  },
  id: 'bsho',
  name: 'British Shorthair',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/BritishShorthair.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/british-shorthair',
  vcahospitals_url:
   'https://vcahospitals.com/know-your-pet/cat-breeds/british-shorthair',
  temperament: 'Affectionate, Easy Going, Gentle, Loyal, Patient, calm',
  origin: 'United Kingdom',
  country_codes: 'GB',
  country_code: 'GB',
  description:
   "The British Shorthair is a very pleasant cat to have as a companion, ans is easy going and placid. The British is a fiercely loyal, loving cat and will attach herself to every one of her family members. While loving to play, she doesn't need hourly attention. If she is in the mood to play, she will find someone and bring a toy to that person. The British also plays well by herself, and thus is a good companion for single people.",
  life_span: '12 - 17',
  indoor: 0,
  lap: 1,
  alt_names: 'Highlander, Highland Straight, Britannica',
  adaptability: 5,
  affection_level: 4,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 2,
  grooming: 2,
  health_issues: 2,
  intelligence: 3,
  shedding_level: 4,
  social_needs: 3,
  stranger_friendly: 2,
  vocalisation: 1,
  experimental: 0,
  hairless: 0,
  natural: 1,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/British_Shorthair',
  hypoallergenic: 0,
  reference_image_id: 's4wQfYoEk',
  image: {
   id: 's4wQfYoEk',
   width: 1600,
   height: 1457,
   url: 'https://cdn2.thecatapi.com/images/s4wQfYoEk.jpg',
  },
 },
 {
  weight: {
   imperial: '6 - 12',
   metric: '3 - 5',
  },
  id: 'bure',
  name: 'Burmese',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/Burmese.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/burmese',
  vcahospitals_url: 'https://vcahospitals.com/know-your-pet/cat-breeds/burmese',
  temperament:
   'Curious, Intelligent, Gentle, Social, Interactive, Playful, Lively',
  origin: 'Burma',
  country_codes: 'MM',
  country_code: 'MM',
  description:
   'Burmese love being with people, playing with them, and keeping them entertained. They crave close physical contact and abhor an empty lap. They will follow their humans from room to room, and sleep in bed with them, preferably under the covers, cuddled as close as possible. At play, they will turn around to see if their human is watching and being entertained by their crazy antics.',
  life_span: '15 - 16',
  indoor: 0,
  lap: 1,
  alt_names: '',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 4,
  grooming: 1,
  health_issues: 3,
  intelligence: 5,
  shedding_level: 3,
  social_needs: 5,
  stranger_friendly: 5,
  vocalisation: 5,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Burmese_(cat)',
  hypoallergenic: 1,
  reference_image_id: '4lXnnfxac',
  image: {
   id: '4lXnnfxac',
   width: 1250,
   height: 650,
   url: 'https://cdn2.thecatapi.com/images/4lXnnfxac.jpg',
  },
 },
 {
  weight: {
   imperial: '6 - 13',
   metric: '3 - 6',
  },
  id: 'buri',
  name: 'Burmilla',
  cfa_url: 'http://cfa.org/Breeds/BreedsAB/Burmilla.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/burmilla',
  temperament: 'Easy Going, Friendly, Intelligent, Lively, Playful, Social',
  origin: 'United Kingdom',
  country_codes: 'GB',
  country_code: 'GB',
  description:
   'The Burmilla is a fairly placid cat. She tends to be an easy cat to get along with, requiring minimal care. The Burmilla is affectionate and sweet and makes a good companion, the Burmilla is an ideal companion to while away a lonely evening. Loyal, devoted, and affectionate, this cat will stay by its owner, always keeping them company.',
  life_span: '10 - 15',
  indoor: 0,
  lap: 1,
  alt_names: '',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 4,
  energy_level: 3,
  grooming: 3,
  health_issues: 3,
  intelligence: 3,
  shedding_level: 3,
  social_needs: 4,
  stranger_friendly: 3,
  vocalisation: 5,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Burmilla',
  hypoallergenic: 0,
  reference_image_id: 'jvg3XfEdC',
  image: {
   id: 'jvg3XfEdC',
   width: 960,
   height: 960,
   url: 'https://cdn2.thecatapi.com/images/jvg3XfEdC.jpg',
  },
 },
 {
  weight: {
   imperial: '10 - 15',
   metric: '5 - 7',
  },
  id: 'cspa',
  name: 'California Spangled',
  temperament: 'Affectionate, Curious, Intelligent, Loyal, Social',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   'Perhaps the only thing about the California spangled cat that isn’t wild-like is its personality. Known to be affectionate, gentle and sociable, this breed enjoys spending a great deal of time with its owners. They are very playful, often choosing to perch in high locations and show off their acrobatic skills.',
  life_span: '10 - 14',
  indoor: 0,
  alt_names: 'Spangle',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 5,
  grooming: 1,
  health_issues: 1,
  intelligence: 5,
  shedding_level: 1,
  social_needs: 3,
  stranger_friendly: 4,
  vocalisation: 1,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/California_Spangled',
  hypoallergenic: 0,
  reference_image_id: 'B1ERTmgph',
  image: {
   id: 'B1ERTmgph',
   width: 1200,
   height: 688,
   url: 'https://cdn2.thecatapi.com/images/B1ERTmgph.jpg',
  },
 },
 {
  weight: {
   imperial: '7 - 12',
   metric: '3 - 5',
  },
  id: 'ctif',
  name: 'Chantilly-Tiffany',
  temperament: 'Affectionate, Demanding, Interactive, Loyal',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   'The Chantilly is a devoted companion and prefers company to being left alone. While the Chantilly is not demanding, she will "chirp" and "talk" as if having a conversation. This breed is affectionate, with a sweet temperament. It can stay still for extended periods, happily lounging in the lap of its loved one. This quality makes the Tiffany an ideal traveling companion, and an ideal house companion for senior citizens and the physically handicapped.',
  life_span: '14 - 16',
  indoor: 0,
  lap: 1,
  alt_names: 'Chantilly, Foreign Longhair',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 4,
  grooming: 5,
  health_issues: 1,
  intelligence: 5,
  shedding_level: 5,
  social_needs: 3,
  stranger_friendly: 4,
  vocalisation: 5,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Chantilly-Tiffany',
  hypoallergenic: 0,
  reference_image_id: 'TR-5nAd_S',
  image: {
   id: 'TR-5nAd_S',
   width: 2901,
   height: 2938,
   url: 'https://cdn2.thecatapi.com/images/TR-5nAd_S.jpg',
  },
 },
 {
  weight: {
   imperial: '6 - 15',
   metric: '3 - 7',
  },
  id: 'char',
  name: 'Chartreux',
  cfa_url: 'http://cfa.org/Breeds/BreedsCJ/Chartreux.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/chartreux',
  vcahospitals_url:
   'https://vcahospitals.com/know-your-pet/cat-breeds/chartreux',
  temperament: 'Affectionate, Loyal, Intelligent, Social, Lively, Playful',
  origin: 'France',
  country_codes: 'FR',
  country_code: 'FR',
  description:
   'The Chartreux is generally silent but communicative. Short play sessions, mixed with naps and meals are their perfect day. Whilst appreciating any attention you give them, they are not demanding, content instead to follow you around devotedly, sleep on your bed and snuggle with you if you’re not feeling well.',
  life_span: '12 - 15',
  indoor: 0,
  lap: 1,
  alt_names: '',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 2,
  grooming: 1,
  health_issues: 2,
  intelligence: 4,
  shedding_level: 3,
  social_needs: 5,
  stranger_friendly: 5,
  vocalisation: 1,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 1,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Chartreux',
  hypoallergenic: 1,
  reference_image_id: 'j6oFGLpRG',
  image: {
   id: 'j6oFGLpRG',
   width: 768,
   height: 1024,
   url: 'https://cdn2.thecatapi.com/images/j6oFGLpRG.jpg',
  },
 },
 {
  weight: {
   imperial: '7 - 15',
   metric: '3 - 7',
  },
  id: 'chau',
  name: 'Chausie',
  temperament: 'Affectionate, Intelligent, Playful, Social',
  origin: 'Egypt',
  country_codes: 'EG',
  country_code: 'EG',
  description:
   'For those owners who desire a feline capable of evoking the great outdoors, the strikingly beautiful Chausie retains a bit of the wild in its appearance but has the house manners of our friendly, familiar moggies. Very playful, this cat needs a large amount of space to be able to fully embrace its hunting instincts.',
  life_span: '12 - 14',
  indoor: 0,
  alt_names: 'Nile Cat',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 4,
  grooming: 3,
  health_issues: 1,
  intelligence: 5,
  shedding_level: 3,
  social_needs: 3,
  stranger_friendly: 4,
  vocalisation: 1,
  experimental: 1,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Chausie',
  hypoallergenic: 0,
  reference_image_id: 'vJ3lEYgXr',
  image: {
   id: 'vJ3lEYgXr',
   width: 1100,
   height: 786,
   url: 'https://cdn2.thecatapi.com/images/vJ3lEYgXr.jpg',
  },
 },
 {
  weight: {
   imperial: '8 - 15',
   metric: '4 - 7',
  },
  id: 'chee',
  name: 'Cheetoh',
  temperament: 'Affectionate, Gentle, Intelligent, Social',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   'The Cheetoh has a super affectionate nature and real love for their human companions; they are intelligent with the ability to learn quickly. You can expect that a Cheetoh will be a fun-loving kitty who enjoys playing, running, and jumping through every room in your house.',
  life_span: '12 - 14',
  indoor: 0,
  alt_names: ' ',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 4,
  grooming: 1,
  health_issues: 1,
  intelligence: 5,
  shedding_level: 1,
  social_needs: 3,
  stranger_friendly: 4,
  vocalisation: 5,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Bengal_cat#Cheetoh',
  hypoallergenic: 0,
  reference_image_id: 'IFXsxmXLm',
  image: {
   id: 'IFXsxmXLm',
   width: 973,
   height: 973,
   url: 'https://cdn2.thecatapi.com/images/IFXsxmXLm.jpg',
  },
 },
 {
  weight: {
   imperial: '4 - 10',
   metric: '2 - 5',
  },
  id: 'csho',
  name: 'Colorpoint Shorthair',
  cfa_url: 'http://cfa.org/Breeds/BreedsCJ/ColorpointShorthair.aspx',
  vcahospitals_url:
   'https://vcahospitals.com/know-your-pet/cat-breeds/colorpoint-shorthair',
  temperament: 'Affectionate, Intelligent, Playful, Social',
  origin: 'United States',
  country_codes: 'US',
  country_code: 'US',
  description:
   'Colorpoint Shorthairs are an affectionate breed, devoted and loyal to their people. Sensitive to their owner’s moods, Colorpoints are more than happy to sit at your side or on your lap and purr words of encouragement on a bad day. They will constantly seek out your lap whenever it is open and in the moments when your lap is preoccupied they will stretch out in sunny spots on the ground.',
  life_span: '12 - 16',
  indoor: 0,
  lap: 1,
  alt_names: '',
  adaptability: 3,
  affection_level: 4,
  child_friendly: 4,
  cat_friendly: 3,
  dog_friendly: 4,
  energy_level: 4,
  grooming: 2,
  health_issues: 2,
  intelligence: 5,
  shedding_level: 3,
  social_needs: 4,
  stranger_friendly: 2,
  vocalisation: 5,
  bidability: 4,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Colorpoint_Shorthair',
  hypoallergenic: 0,
  reference_image_id: 'oSpqGyUDS',
  image: {
   id: 'oSpqGyUDS',
   width: 1363,
   height: 1600,
   url: 'https://cdn2.thecatapi.com/images/oSpqGyUDS.jpg',
  },
 },
 {
  weight: {
   imperial: '5 - 9',
   metric: '2 - 4',
  },
  id: 'crex',
  name: 'Cornish Rex',
  cfa_url: 'http://cfa.org/Breeds/BreedsCJ/CornishRex.aspx',
  vetstreet_url: 'http://www.vetstreet.com/cats/cornish-rex',
  vcahospitals_url:
   'https://vcahospitals.com/know-your-pet/cat-breeds/cornish-rex',
  temperament: 'Affectionate, Intelligent, Active, Curious, Playful',
  origin: 'United Kingdom',
  country_codes: 'GB',
  country_code: 'GB',
  description:
   'This is a confident cat who loves people and will follow them around, waiting for any opportunity to sit in a lap or give a kiss. He enjoys being handled, making it easy to take him to the veterinarian or train him for therapy work. The Cornish Rex stay in kitten mode most of their lives and well into their senior years. ',
  life_span: '11 - 14',
  indoor: 0,
  lap: 1,
  alt_names: '',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  cat_friendly: 2,
  dog_friendly: 5,
  energy_level: 5,
  grooming: 1,
  health_issues: 2,
  intelligence: 5,
  shedding_level: 1,
  social_needs: 5,
  stranger_friendly: 3,
  vocalisation: 1,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 1,
  suppressed_tail: 0,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Cornish_Rex',
  hypoallergenic: 1,
  reference_image_id: 'unX21IBVB',
  image: {
   id: 'unX21IBVB',
   width: 2976,
   height: 1784,
   url: 'https://cdn2.thecatapi.com/images/unX21IBVB.jpg',
  },
 },
 {
  weight: {
   imperial: '8 - 13',
   metric: '4 - 6',
  },
  id: 'cymr',
  name: 'Cymric',
  vetstreet_url: 'http://www.vetstreet.com/cats/cymric',
  temperament: 'Gentle, Loyal, Intelligent, Playful',
  origin: 'Canada',
  country_codes: 'CA',
  country_code: 'CA',
  description:
   'The Cymric is a placid, sweet cat. They do not get too upset about anything that happens in their world. They are loving companions and adore people. They are smart and dexterous, capable of using his paws to get into cabinets or to open doors.',
  life_span: '8 - 14',
  indoor: 0,
  lap: 1,
  alt_names: 'Spangle',
  adaptability: 5,
  affection_level: 5,
  child_friendly: 4,
  dog_friendly: 5,
  energy_level: 5,
  grooming: 3,
  health_issues: 3,
  intelligence: 5,
  shedding_level: 5,
  social_needs: 5,
  stranger_friendly: 3,
  vocalisation: 3,
  experimental: 0,
  hairless: 0,
  natural: 0,
  rare: 0,
  rex: 0,
  suppressed_tail: 1,
  short_legs: 0,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Cymric_(cat)',
  hypoallergenic: 0,
  reference_image_id: '3dbtapCWM',
  image: {
   id: '3dbtapCWM',
   width: 1440,
   height: 900,
   url: 'https://cdn2.thecatapi.com/images/3dbtapCWM.jpg',
  },
 },
]

export const mockImages = [
 {
  breeds: [],
  id: 'md',
  url: 'https://cdn2.thecatapi.com/images/md.jpg',
  width: 500,
  height: 333,
 },
 {
  breeds: [],
  categories: [
   {
    id: 6,
    name: 'caturday',
   },
  ],
  id: 'ra',
  url: 'https://cdn2.thecatapi.com/images/ra.jpg',
  width: 640,
  height: 479,
 },
 {
  breeds: [],
  id: '17l',
  url: 'https://cdn2.thecatapi.com/images/17l.jpg',
  width: 600,
  height: 760,
 },
 {
  breeds: [],
  id: '1b9',
  url: 'https://cdn2.thecatapi.com/images/1b9.png',
  width: 1024,
  height: 765,
 },
 {
  breeds: [],
  categories: [
   {
    id: 9,
    name: 'dream',
   },
  ],
  id: '1qq',
  url: 'https://cdn2.thecatapi.com/images/1qq.jpg',
  width: 500,
  height: 332,
 },
 {
  breeds: [],
  id: '21v',
  url: 'https://cdn2.thecatapi.com/images/21v.jpg',
  width: 514,
  height: 323,
 },
 {
  breeds: [],
  id: '23r',
  url: 'https://cdn2.thecatapi.com/images/23r.jpg',
  width: 624,
  height: 425,
 },
 {
  breeds: [],
  id: '2ft',
  url: 'https://cdn2.thecatapi.com/images/2ft.jpg',
  width: 500,
  height: 333,
 },
 {
  breeds: [],
  id: '2k0',
  url: 'https://cdn2.thecatapi.com/images/2k0.jpg',
  width: 500,
  height: 333,
 },
 {
  breeds: [],
  id: '2m1',
  url: 'https://cdn2.thecatapi.com/images/2m1.jpg',
  width: 480,
  height: 360,
 },
 {
  breeds: [],
  id: '2om',
  url: 'https://cdn2.thecatapi.com/images/2om.gif',
  width: 204,
  height: 137,
 },
 {
  breeds: [],
  categories: [
   {
    id: 1,
    name: 'hats',
   },
  ],
  id: '391',
  url: 'https://cdn2.thecatapi.com/images/391.jpg',
  width: 1024,
  height: 946,
 },
 {
  breeds: [],
  categories: [
   {
    id: 1,
    name: 'hats',
   },
  ],
  id: '39n',
  url: 'https://cdn2.thecatapi.com/images/39n.jpg',
  width: 610,
  height: 620,
 },
 {
  breeds: [],
  id: '3qe',
  url: 'https://cdn2.thecatapi.com/images/3qe.jpg',
  width: 500,
  height: 358,
 },
 {
  breeds: [],
  id: '3qm',
  url: 'https://cdn2.thecatapi.com/images/3qm.gif',
  width: 500,
  height: 281,
 },
 {
  breeds: [],
  id: '3tv',
  url: 'https://cdn2.thecatapi.com/images/3tv.jpg',
  width: 612,
  height: 612,
 },
 {
  breeds: [],
  id: '3vv',
  url: 'https://cdn2.thecatapi.com/images/3vv.jpg',
  width: 500,
  height: 334,
 },
 {
  breeds: [],
  categories: [
   {
    id: 6,
    name: 'caturday',
   },
  ],
  id: '455',
  url: 'https://cdn2.thecatapi.com/images/455.jpg',
  width: 450,
  height: 600,
 },
 {
  breeds: [],
  id: '4bo',
  url: 'https://cdn2.thecatapi.com/images/4bo.gif',
  width: 479,
  height: 340,
 },
 {
  breeds: [],
  categories: [
   {
    id: 6,
    name: 'caturday',
   },
  ],
  id: '5ta',
  url: 'https://cdn2.thecatapi.com/images/5ta.jpg',
  width: 600,
  height: 401,
 },
 {
  breeds: [],
  id: '61h',
  url: 'https://cdn2.thecatapi.com/images/61h.gif',
  width: 400,
  height: 309,
 },
 {
  breeds: [],
  id: '65a',
  url: 'https://cdn2.thecatapi.com/images/65a.png',
  width: 1024,
  height: 768,
 },
 {
  breeds: [],
  id: '6f1',
  url: 'https://cdn2.thecatapi.com/images/6f1.jpg',
  width: 2592,
  height: 1952,
 },
 {
  breeds: [],
  id: '6qf',
  url: 'https://cdn2.thecatapi.com/images/6qf.jpg',
  width: 604,
  height: 340,
 },
 {
  breeds: [],
  id: '6rr',
  url: 'https://cdn2.thecatapi.com/images/6rr.jpg',
  width: 640,
  height: 492,
 },
 {
  breeds: [],
  id: '6u9',
  url: 'https://cdn2.thecatapi.com/images/6u9.jpg',
  width: 1200,
  height: 800,
 },
 {
  breeds: [],
  id: '75j',
  url: 'https://cdn2.thecatapi.com/images/75j.jpg',
  width: 500,
  height: 309,
 },
 {
  breeds: [],
  categories: [
   {
    id: 1,
    name: 'hats',
   },
  ],
  id: '7gn',
  url: 'https://cdn2.thecatapi.com/images/7gn.jpg',
  width: 387,
  height: 592,
 },
 {
  breeds: [],
  categories: [
   {
    id: 1,
    name: 'hats',
   },
  ],
  id: '7ie',
  url: 'https://cdn2.thecatapi.com/images/7ie.jpg',
  width: 500,
  height: 375,
 },
 {
  breeds: [],
  id: '7nm',
  url: 'https://cdn2.thecatapi.com/images/7nm.jpg',
  width: 500,
  height: 277,
 },
 {
  breeds: [],
  id: '8k7',
  url: 'https://cdn2.thecatapi.com/images/8k7.jpg',
  width: 500,
  height: 334,
 },
 {
  breeds: [],
  categories: [
   {
    id: 15,
    name: 'clothes',
   },
  ],
  id: '8ud',
  url: 'https://cdn2.thecatapi.com/images/8ud.jpg',
  width: 1366,
  height: 853,
 },
 {
  breeds: [],
  id: '9dl',
  url: 'https://cdn2.thecatapi.com/images/9dl.jpg',
  width: 480,
  height: 567,
 },
 {
  breeds: [],
  id: '9oj',
  url: 'https://cdn2.thecatapi.com/images/9oj.gif',
  width: 260,
  height: 189,
 },
 {
  breeds: [],
  id: 'a2q',
  url: 'https://cdn2.thecatapi.com/images/a2q.jpg',
  width: 1356,
  height: 2048,
 },
 {
  breeds: [],
  id: 'a6j',
  url: 'https://cdn2.thecatapi.com/images/a6j.jpg',
  width: 450,
  height: 338,
 },
 {
  breeds: [],
  id: 'a72',
  url: 'https://cdn2.thecatapi.com/images/a72.jpg',
  width: 800,
  height: 800,
 },
 {
  breeds: [],
  id: 'aa1',
  url: 'https://cdn2.thecatapi.com/images/aa1.jpg',
  width: 533,
  height: 800,
 },
 {
  breeds: [],
  id: 'abg',
  url: 'https://cdn2.thecatapi.com/images/abg.jpg',
  width: 510,
  height: 383,
 },
 {
  breeds: [],
  id: 'ad0',
  url: 'https://cdn2.thecatapi.com/images/ad0.jpg',
  width: 450,
  height: 299,
 },
 {
  breeds: [],
  id: 'ae1',
  url: 'https://cdn2.thecatapi.com/images/ae1.jpg',
  width: 500,
  height: 375,
 },
 {
  breeds: [],
  id: 'ait',
  url: 'https://cdn2.thecatapi.com/images/ait.gif',
  width: 500,
  height: 281,
 },
 {
  breeds: [],
  id: 'an7',
  url: 'https://cdn2.thecatapi.com/images/an7.jpg',
  width: 500,
  height: 333,
 },
 {
  breeds: [],
  id: 'ao9',
  url: 'https://cdn2.thecatapi.com/images/ao9.gif',
  width: 245,
  height: 245,
 },
 {
  breeds: [],
  id: 'aqk',
  url: 'https://cdn2.thecatapi.com/images/aqk.jpg',
  width: 570,
  height: 432,
 },
 {
  breeds: [],
  id: 'asv',
  url: 'https://cdn2.thecatapi.com/images/asv.jpg',
  width: 612,
  height: 612,
 },
 {
  breeds: [],
  id: 'auu',
  url: 'https://cdn2.thecatapi.com/images/auu.jpg',
  width: 640,
  height: 480,
 },
 {
  breeds: [],
  id: 'b15',
  url: 'https://cdn2.thecatapi.com/images/b15.jpg',
  width: 480,
  height: 854,
 },
 {
  breeds: [],
  id: 'b19',
  url: 'https://cdn2.thecatapi.com/images/b19.jpg',
  width: 500,
  height: 375,
 },
 {
  breeds: [],
  id: 'bfu',
  url: 'https://cdn2.thecatapi.com/images/bfu.jpg',
  width: 500,
  height: 333,
 },
 {
  breeds: [],
  id: 'bhm',
  url: 'https://cdn2.thecatapi.com/images/bhm.jpg',
  width: 500,
  height: 333,
 },
 {
  breeds: [],
  id: 'bjt',
  url: 'https://cdn2.thecatapi.com/images/bjt.jpg',
  width: 628,
  height: 471,
 },
 {
  breeds: [],
  id: 'bnf',
  url: 'https://cdn2.thecatapi.com/images/bnf.jpg',
  width: 480,
  height: 640,
 },
 {
  breeds: [],
  id: 'bqc',
  url: 'https://cdn2.thecatapi.com/images/bqc.jpg',
  width: 1024,
  height: 681,
 },
 {
  breeds: [],
  id: 'c8j',
  url: 'https://cdn2.thecatapi.com/images/c8j.jpg',
  width: 640,
  height: 640,
 },
 {
  breeds: [],
  id: 'cb7',
  url: 'https://cdn2.thecatapi.com/images/cb7.jpg',
  width: 800,
  height: 808,
 },
 {
  breeds: [],
  id: 'cdu',
  url: 'https://cdn2.thecatapi.com/images/cdu.jpg',
  width: 500,
  height: 325,
 },
 {
  breeds: [],
  id: 'cfq',
  url: 'https://cdn2.thecatapi.com/images/cfq.jpg',
  width: 450,
  height: 438,
 },
 {
  breeds: [],
  id: 'chs',
  url: 'https://cdn2.thecatapi.com/images/chs.jpg',
  width: 900,
  height: 611,
 },
 {
  breeds: [],
  id: 'clm',
  url: 'https://cdn2.thecatapi.com/images/clm.jpg',
  width: 620,
  height: 464,
 },
 {
  breeds: [],
  id: 'd57',
  url: 'https://cdn2.thecatapi.com/images/d57.jpg',
  width: 2604,
  height: 3000,
 },
 {
  breeds: [],
  categories: [
   {
    id: 5,
    name: 'boxes',
   },
  ],
  id: 'd70',
  url: 'https://cdn2.thecatapi.com/images/d70.jpg',
  width: 480,
  height: 640,
 },
 {
  breeds: [],
  id: 'dea',
  url: 'https://cdn2.thecatapi.com/images/dea.jpg',
  width: 2400,
  height: 1800,
 },
 {
  breeds: [],
  id: 'dg8',
  url: 'https://cdn2.thecatapi.com/images/dg8.jpg',
  width: 800,
  height: 517,
 },
 {
  breeds: [],
  id: 'dmo',
  url: 'https://cdn2.thecatapi.com/images/dmo.jpg',
  width: 640,
  height: 480,
 },
 {
  breeds: [],
  id: 'dp8',
  url: 'https://cdn2.thecatapi.com/images/dp8.jpg',
  width: 640,
  height: 426,
 },
 {
  breeds: [],
  id: 'dua',
  url: 'https://cdn2.thecatapi.com/images/dua.jpg',
  width: 422,
  height: 640,
 },
 {
  breeds: [],
  id: 'duv',
  url: 'https://cdn2.thecatapi.com/images/duv.jpg',
  width: 640,
  height: 427,
 },
 {
  breeds: [],
  id: 'e45',
  url: 'https://cdn2.thecatapi.com/images/e45.jpg',
  width: 638,
  height: 444,
 },
 {
  breeds: [],
  id: 'MTYzMzA5OA',
  url: 'https://cdn2.thecatapi.com/images/MTYzMzA5OA.jpg',
  width: 500,
  height: 400,
 },
 {
  breeds: [],
  id: 'MTYzNzMxMg',
  url: 'https://cdn2.thecatapi.com/images/MTYzNzMxMg.jpg',
  width: 1024,
  height: 768,
 },
 {
  breeds: [],
  id: 'MTY3MTcwMg',
  url: 'https://cdn2.thecatapi.com/images/MTY3MTcwMg.jpg',
  width: 640,
  height: 427,
 },
 {
  breeds: [],
  id: 'MTc0NTYwMA',
  url: 'https://cdn2.thecatapi.com/images/MTc0NTYwMA.gif',
  width: 500,
  height: 300,
 },
 {
  breeds: [],
  id: 'MTg0MzE4MQ',
  url: 'https://cdn2.thecatapi.com/images/MTg0MzE4MQ.jpg',
  width: 640,
  height: 529,
 },
 {
  breeds: [],
  id: 'MTg0NTAzMA',
  url: 'https://cdn2.thecatapi.com/images/MTg0NTAzMA.jpg',
  width: 720,
  height: 476,
 },
 {
  breeds: [],
  id: 'MTg5MjQ2MQ',
  url: 'https://cdn2.thecatapi.com/images/MTg5MjQ2MQ.jpg',
  width: 500,
  height: 444,
 },
 {
  breeds: [],
  id: 'MTg5MzE4Ng',
  url: 'https://cdn2.thecatapi.com/images/MTg5MzE4Ng.jpg',
  width: 1500,
  height: 1125,
 },
 {
  breeds: [],
  id: 'MTg5OTUwMw',
  url: 'https://cdn2.thecatapi.com/images/MTg5OTUwMw.jpg',
  width: 450,
  height: 300,
 },
 {
  breeds: [],
  id: 'MTk4NjA0OQ',
  url: 'https://cdn2.thecatapi.com/images/MTk4NjA0OQ.jpg',
  width: 421,
  height: 559,
 },
 {
  breeds: [],
  id: 'MTk5Mzc4Mw',
  url: 'https://cdn2.thecatapi.com/images/MTk5Mzc4Mw.jpg',
  width: 590,
  height: 648,
 },
 {
  breeds: [],
  id: 'MjAwNzc5Ng',
  url: 'https://cdn2.thecatapi.com/images/MjAwNzc5Ng.jpg',
  width: 2333,
  height: 2157,
 },
 {
  breeds: [],
  id: 'MjAzNzA4Mg',
  url: 'https://cdn2.thecatapi.com/images/MjAzNzA4Mg.jpg',
  width: 1458,
  height: 1089,
 },
 {
  breeds: [],
  id: 'MjA0NTcxNg',
  url: 'https://cdn2.thecatapi.com/images/MjA0NTcxNg.jpg',
  width: 750,
  height: 1000,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '4 - 10',
     metric: '2 - 5',
    },
    id: 'bali',
    name: 'Balinese',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/Balinese.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/balinese',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/balinese',
    temperament: 'Affectionate, Intelligent, Playful',
    origin: 'United States',
    country_codes: 'US',
    country_code: 'US',
    description:
     'Balinese are curious, outgoing, intelligent cats with excellent communication skills. They are known for their chatty personalities and are always eager to tell you their views on life, love, and what you’ve served them for dinner. ',
    life_span: '10 - 15',
    indoor: 0,
    alt_names: 'Long-haired Siamese',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 5,
    grooming: 3,
    health_issues: 3,
    intelligence: 5,
    shedding_level: 3,
    social_needs: 5,
    stranger_friendly: 5,
    vocalisation: 5,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Balinese_(cat)',
    hypoallergenic: 1,
    reference_image_id: '13MkvUreZ',
   },
  ],
  id: 'mCbyxNhMR',
  url: 'https://cdn2.thecatapi.com/images/mCbyxNhMR.jpg',
  width: 550,
  height: 750,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '6 - 12',
     metric: '3 - 7',
    },
    id: 'beng',
    name: 'Bengal',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/Bengal.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/bengal',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/bengal',
    temperament: 'Alert, Agile, Energetic, Demanding, Intelligent',
    origin: 'United States',
    country_codes: 'US',
    country_code: 'US',
    description:
     "Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
    life_span: '12 - 15',
    indoor: 0,
    lap: 0,
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    cat_friendly: 4,
    dog_friendly: 5,
    energy_level: 5,
    grooming: 1,
    health_issues: 3,
    intelligence: 5,
    shedding_level: 3,
    social_needs: 5,
    stranger_friendly: 3,
    vocalisation: 5,
    bidability: 3,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Bengal_(cat)',
    hypoallergenic: 1,
    reference_image_id: 'O3btzLlsO',
   },
  ],
  id: 'J2PmlIizw',
  url: 'https://cdn2.thecatapi.com/images/J2PmlIizw.jpg',
  width: 1080,
  height: 1350,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '12 - 20',
     metric: '5 - 9',
    },
    id: 'bsho',
    name: 'British Shorthair',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/BritishShorthair.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/british-shorthair',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/british-shorthair',
    temperament: 'Affectionate, Easy Going, Gentle, Loyal, Patient, calm',
    origin: 'United Kingdom',
    country_codes: 'GB',
    country_code: 'GB',
    description:
     "The British Shorthair is a very pleasant cat to have as a companion, ans is easy going and placid. The British is a fiercely loyal, loving cat and will attach herself to every one of her family members. While loving to play, she doesn't need hourly attention. If she is in the mood to play, she will find someone and bring a toy to that person. The British also plays well by herself, and thus is a good companion for single people.",
    life_span: '12 - 17',
    indoor: 0,
    lap: 1,
    alt_names: 'Highlander, Highland Straight, Britannica',
    adaptability: 5,
    affection_level: 4,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 2,
    grooming: 2,
    health_issues: 2,
    intelligence: 3,
    shedding_level: 4,
    social_needs: 3,
    stranger_friendly: 2,
    vocalisation: 1,
    experimental: 0,
    hairless: 0,
    natural: 1,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/British_Shorthair',
    hypoallergenic: 0,
    reference_image_id: 's4wQfYoEk',
   },
  ],
  id: 'M1Rh3CPp_',
  url: 'https://cdn2.thecatapi.com/images/M1Rh3CPp_.jpg',
  width: 2352,
  height: 1568,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '5 - 10',
     metric: '2 - 5',
    },
    id: 'jbob',
    name: 'Japanese Bobtail',
    cfa_url: 'http://cfa.org/Breeds/BreedsCJ/JapaneseBobtail.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/japanese-bobtail',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/japanese-bobtail',
    temperament:
     'Active, Agile, Clever, Easy Going, Intelligent, Lively, Loyal, Playful, Social',
    origin: 'Japan',
    country_codes: 'JP',
    country_code: 'JP',
    description:
     'The Japanese Bobtail is an active, sweet, loving and highly intelligent breed. They love to be with people and play seemingly endlessly. They learn their name and respond to it. They bring toys to people and play fetch with a favorite toy for hours. Bobtails are social and are at their best when in the company of people. They take over the house and are not intimidated. If a dog is in the house, Bobtails assume Bobtails are in charge.',
    life_span: '14 - 16',
    indoor: 0,
    lap: 1,
    alt_names: 'Japanese Truncated Cat',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 5,
    grooming: 1,
    health_issues: 1,
    intelligence: 5,
    shedding_level: 3,
    social_needs: 5,
    stranger_friendly: 5,
    vocalisation: 5,
    experimental: 0,
    hairless: 0,
    natural: 1,
    rare: 0,
    rex: 0,
    suppressed_tail: 1,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Japanese_Bobtail',
    hypoallergenic: 0,
    reference_image_id: '-tm9-znzl',
   },
  ],
  id: 'VwGK1QO3m',
  url: 'https://cdn2.thecatapi.com/images/VwGK1QO3m.jpg',
  width: 1600,
  height: 1200,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '6 - 10',
     metric: '3 - 5',
    },
    id: 'lape',
    name: 'LaPerm',
    cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/LaPerm.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/laperm',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/laperm',
    temperament: 'Affectionate, Friendly, Gentle, Intelligent, Playful, Quiet',
    origin: 'Thailand',
    country_codes: 'TH',
    country_code: 'TH',
    description:
     'LaPerms are gentle and affectionate but also very active. Unlike many active breeds, the LaPerm is also quite content to be a lap cat. The LaPerm will often follow your lead; that is, if they are busy playing and you decide to sit and relax, simply pick up your LaPerm and sit down with it, and it will stay in your lap, devouring the attention you give it.',
    life_span: '10 - 15',
    indoor: 0,
    lap: 1,
    alt_names: 'Si-Sawat',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 4,
    grooming: 1,
    health_issues: 1,
    intelligence: 5,
    shedding_level: 3,
    social_needs: 4,
    stranger_friendly: 4,
    vocalisation: 3,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 1,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/LaPerm',
    hypoallergenic: 1,
    reference_image_id: 'aKbsEYjSl',
   },
  ],
  id: 'g4vhUKcZX',
  url: 'https://cdn2.thecatapi.com/images/g4vhUKcZX.jpg',
  width: 1136,
  height: 852,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '5 - 9',
     metric: '2 - 4',
    },
    id: 'munc',
    name: 'Munchkin',
    vetstreet_url: 'http://www.vetstreet.com/cats/munchkin',
    temperament: 'Agile, Easy Going, Intelligent, Playful',
    origin: 'United States',
    country_codes: 'US',
    country_code: 'US',
    description:
     'The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.',
    life_span: '10 - 15',
    indoor: 0,
    lap: 1,
    alt_names: '',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 4,
    grooming: 2,
    health_issues: 3,
    intelligence: 5,
    shedding_level: 3,
    social_needs: 5,
    stranger_friendly: 5,
    vocalisation: 3,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 1,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Munchkin_(cat)',
    hypoallergenic: 0,
    reference_image_id: 'j5cVSqLer',
   },
  ],
  id: 'yFqH0s2H_',
  url: 'https://cdn2.thecatapi.com/images/yFqH0s2H_.jpg',
  width: 960,
  height: 960,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '8 - 16',
     metric: '4 - 7',
    },
    id: 'norw',
    name: 'Norwegian Forest Cat',
    cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/NorwegianForestCat.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/norwegian-forest-cat',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/norwegian-forest-cat',
    temperament: 'Sweet, Active, Intelligent, Social, Playful, Lively, Curious',
    origin: 'Norway',
    country_codes: 'NO',
    country_code: 'NO',
    description:
     'The Norwegian Forest Cat is a sweet, loving cat. She appreciates praise and loves to interact with her parent. She makes a loving companion and bonds with her parents once she accepts them for her own. She is still a hunter at heart. She loves to chase toys as if they are real. She is territorial and patrols several times each day to make certain that all is fine.',
    life_span: '12 - 16',
    indoor: 0,
    alt_names: 'Skogkatt / Skaukatt, Norsk Skogkatt / Norsk Skaukatt, Weegie',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 3,
    grooming: 2,
    health_issues: 3,
    intelligence: 4,
    shedding_level: 3,
    social_needs: 5,
    stranger_friendly: 5,
    vocalisation: 1,
    experimental: 0,
    hairless: 0,
    natural: 1,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Norwegian_Forest_Cat',
    hypoallergenic: 0,
    reference_image_id: '06dgGmEOV',
   },
  ],
  id: 'JnD5BF9Uq',
  url: 'https://cdn2.thecatapi.com/images/JnD5BF9Uq.jpg',
  width: 1200,
  height: 800,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '8 - 16',
     metric: '4 - 7',
    },
    id: 'norw',
    name: 'Norwegian Forest Cat',
    cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/NorwegianForestCat.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/norwegian-forest-cat',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/norwegian-forest-cat',
    temperament: 'Sweet, Active, Intelligent, Social, Playful, Lively, Curious',
    origin: 'Norway',
    country_codes: 'NO',
    country_code: 'NO',
    description:
     'The Norwegian Forest Cat is a sweet, loving cat. She appreciates praise and loves to interact with her parent. She makes a loving companion and bonds with her parents once she accepts them for her own. She is still a hunter at heart. She loves to chase toys as if they are real. She is territorial and patrols several times each day to make certain that all is fine.',
    life_span: '12 - 16',
    indoor: 0,
    alt_names: 'Skogkatt / Skaukatt, Norsk Skogkatt / Norsk Skaukatt, Weegie',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 3,
    grooming: 2,
    health_issues: 3,
    intelligence: 4,
    shedding_level: 3,
    social_needs: 5,
    stranger_friendly: 5,
    vocalisation: 1,
    experimental: 0,
    hairless: 0,
    natural: 1,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Norwegian_Forest_Cat',
    hypoallergenic: 0,
    reference_image_id: '06dgGmEOV',
   },
  ],
  id: '7x-75d7vB',
  url: 'https://cdn2.thecatapi.com/images/7x-75d7vB.jpg',
  width: 1250,
  height: 650,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '5 - 8',
     metric: '2 - 4',
    },
    id: 'sing',
    name: 'Singapura',
    cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/Singapura.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/singapura',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/singapura',
    temperament:
     'Affectionate, Curious, Easy Going, Intelligent, Interactive, Lively, Loyal',
    origin: 'Singapore',
    country_codes: 'SP',
    country_code: 'SP',
    description:
     'The Singapura is usually cautious when it comes to meeting new people, but loves attention from his family so much that she sometimes has the reputation of being a pest. This is a highly active, curious and affectionate cat. She may be small, but she knows she’s in charge',
    life_span: '12 - 15',
    indoor: 0,
    lap: 1,
    alt_names: 'Drain Cat, Kucinta, Pura',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 5,
    grooming: 1,
    health_issues: 1,
    intelligence: 5,
    shedding_level: 3,
    social_needs: 5,
    stranger_friendly: 5,
    vocalisation: 1,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Singapura_(cat)',
    hypoallergenic: 0,
    reference_image_id: 'Qtncp2nRe',
   },
  ],
  id: '6jbkliQh5',
  url: 'https://cdn2.thecatapi.com/images/6jbkliQh5.jpg',
  width: 2048,
  height: 1366,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '7 - 12',
     metric: '3 - 5',
    },
    id: 'snow',
    name: 'Snowshoe',
    temperament: 'Affectionate, Social, Intelligent, Sweet-tempered',
    origin: 'United States',
    country_codes: 'US',
    country_code: 'US',
    description:
     'The Snowshoe is a vibrant, energetic, affectionate and intelligent cat. They love being around people which makes them ideal for families, and becomes unhappy when left alone for long periods of time. Usually attaching themselves to one person, they do whatever they can to get your attention.',
    life_span: '14 - 19',
    indoor: 0,
    lap: 1,
    alt_names: '',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 4,
    grooming: 3,
    health_issues: 1,
    intelligence: 5,
    shedding_level: 3,
    social_needs: 4,
    stranger_friendly: 4,
    vocalisation: 5,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Snowshoe_(cat)',
    hypoallergenic: 0,
    reference_image_id: 'MK-sYESvO',
   },
  ],
  id: 't4f-Ov8YD',
  url: 'https://cdn2.thecatapi.com/images/t4f-Ov8YD.jpg',
  width: 750,
  height: 750,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '6 - 16',
     metric: '3 - 7',
    },
    id: 'srex',
    name: 'Selkirk Rex',
    cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/SelkirkRex.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/selkirk-rex',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/selkirk-rex',
    temperament:
     'Active, Affectionate, Dependent, Gentle, Patient, Playful, Quiet, Social',
    origin: 'United States',
    country_codes: 'US',
    country_code: 'US',
    description:
     'The Selkirk Rex is an incredibly patient, loving, and tolerant breed. The Selkirk also has a silly side and is sometimes described as clownish. She loves being a lap cat and will be happy to chat with you in a quiet voice if you talk to her. ',
    life_span: '14 - 15',
    indoor: 0,
    lap: 1,
    alt_names: 'Shepherd Cat',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 3,
    grooming: 2,
    health_issues: 4,
    intelligence: 3,
    shedding_level: 1,
    social_needs: 3,
    stranger_friendly: 3,
    vocalisation: 3,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 1,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Selkirk_Rex',
    hypoallergenic: 1,
    reference_image_id: 'II9dOZmrw',
   },
  ],
  id: 'nhwAjEuEG',
  url: 'https://cdn2.thecatapi.com/images/nhwAjEuEG.jpg',
  width: 1080,
  height: 1080,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '6 - 16',
     metric: '3 - 7',
    },
    id: 'srex',
    name: 'Selkirk Rex',
    cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/SelkirkRex.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/selkirk-rex',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/selkirk-rex',
    temperament:
     'Active, Affectionate, Dependent, Gentle, Patient, Playful, Quiet, Social',
    origin: 'United States',
    country_codes: 'US',
    country_code: 'US',
    description:
     'The Selkirk Rex is an incredibly patient, loving, and tolerant breed. The Selkirk also has a silly side and is sometimes described as clownish. She loves being a lap cat and will be happy to chat with you in a quiet voice if you talk to her. ',
    life_span: '14 - 15',
    indoor: 0,
    lap: 1,
    alt_names: 'Shepherd Cat',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 3,
    grooming: 2,
    health_issues: 4,
    intelligence: 3,
    shedding_level: 1,
    social_needs: 3,
    stranger_friendly: 3,
    vocalisation: 3,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 1,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Selkirk_Rex',
    hypoallergenic: 1,
    reference_image_id: 'II9dOZmrw',
   },
  ],
  id: 'xfkK4cQvp',
  url: 'https://cdn2.thecatapi.com/images/xfkK4cQvp.jpg',
  width: 750,
  height: 904,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '6 - 12',
     metric: '3 - 5',
    },
    id: 'soma',
    name: 'Somali',
    cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/Somali.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/somali',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/somali',
    temperament:
     'Mischievous, Tenacious, Intelligent, Affectionate, Gentle, Interactive, Loyal',
    origin: 'Somalia',
    country_codes: 'SO',
    country_code: 'SO',
    description:
     'The Somali lives life to the fullest. He climbs higher, jumps farther, plays harder. Nothing escapes the notice of this highly intelligent and inquisitive cat. Somalis love the company of humans and other animals.',
    life_span: '12 - 16',
    indoor: 0,
    alt_names: 'Fox Cat, Long-Haired Abyssinian',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 3,
    dog_friendly: 4,
    energy_level: 5,
    grooming: 3,
    health_issues: 2,
    intelligence: 5,
    shedding_level: 4,
    social_needs: 5,
    stranger_friendly: 5,
    vocalisation: 1,
    experimental: 0,
    hairless: 0,
    natural: 0,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Somali_(cat)',
    hypoallergenic: 0,
    reference_image_id: 'EPF2ejNS0',
   },
  ],
  id: '0lKfGvesZ',
  url: 'https://cdn2.thecatapi.com/images/0lKfGvesZ.jpg',
  width: 2048,
  height: 1360,
 },
 {
  breeds: [
   {
    weight: {
     imperial: '7 - 20',
     metric: '3 - 9',
    },
    id: 'tvan',
    name: 'Turkish Van',
    cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/TurkishVan.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/turkish-van',
    vcahospitals_url:
     'https://vcahospitals.com/know-your-pet/cat-breeds/turkish-van',
    temperament: 'Agile, Intelligent, Loyal, Playful, Energetic',
    origin: 'Turkey',
    country_codes: 'TR',
    country_code: 'TR',
    description:
     'While the Turkish Van loves to jump and climb, play with toys, retrieve and play chase, she is is big and ungainly; this is one cat who doesn’t always land on his feet. While not much of a lap cat, the Van will be happy to cuddle next to you and sleep in your bed. ',
    life_span: '12 - 17',
    indoor: 0,
    alt_names: 'Turkish Cat, Swimming cat',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 5,
    grooming: 2,
    health_issues: 1,
    intelligence: 5,
    shedding_level: 3,
    social_needs: 4,
    stranger_friendly: 4,
    vocalisation: 5,
    experimental: 0,
    hairless: 0,
    natural: 1,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Turkish_Van',
    hypoallergenic: 0,
    reference_image_id: 'sxIXJax6h',
   },
  ],
  id: 'r9PDjW3xP',
  url: 'https://cdn2.thecatapi.com/images/r9PDjW3xP.jpg',
  width: 750,
  height: 937,
 },
 {
  breeds: [],
  id: 'huNquXtlK',
  url: 'https://cdn2.thecatapi.com/images/huNquXtlK.jpg',
  width: 123,
  height: 130,
 },
 {
  breeds: [],
  id: 'OYYtgEaOe',
  url: 'https://cdn2.thecatapi.com/images/OYYtgEaOe.jpg',
  width: 400,
  height: 397,
  sub_id: 'demo-564939',
  created_at: '2022-09-21T17:43:22.000Z',
  original_filename: 'StitchCat.jpg',
  breed_ids: null,
 },
 {
  breeds: [],
  id: 'JQnN1Xc1H',
  url: 'https://cdn2.thecatapi.com/images/JQnN1Xc1H.jpg',
  width: 600,
  height: 450,
 },
]
